### ISSUE TITLE
Error when trying to login

### ISSUE THREAD

**Issue by billbarni** [whirly/teamview.nodejs#4]
I get the following error when trying to login:

`Object { _body: "{\"error\":\"badRequest\"}", status: 400, ok: false, statusText: "Bad Request", headers: {…}, type: 2, url: "https://api.monpetitgazon.com/user/signIn" }`

'https://api.monpetitgazon.com/' is statically defined at `pelouse.service.ts` and `sync.ts`

**Comment by whirly** [comment]
Just tried the released version which is here : http://www.mespetitesstats.com and it is still working. You can receive a bad request if the login is not a valid email.

**Comment by billbarni** [comment]
I cloned the repo, installed dependencies, configured database connection... and the error happens.
